version: '0.1'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - "1433:1433"
    environment:
      - "SA_PASSWORD:Password12!"
      - "ACCEPT_EULA: Y"
    restart: unless-stopped
    volumes:
      - db:/var/opt/mssql

  redis:
    image: valkey/valkey:latest
    ports: 
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis:/data
    
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports: 
      - "8081:8081"
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  db:
  redis: